{% set name = "fazy" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fazy-{{ version }}.tar.gz
  sha256: 3967af59c14fd4372a2e10af4ef1be96ce5ab8aa36e6c3fe57c92cdd91ace22f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools ==68.0.0
    - pip
  run:
    - python >=3.7

test:
  imports:
    - f
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pomponchik/fazy
  summary: Lazy f-strings for everyone
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
